version = 1

test_patterns = ["archive/**"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["browser"]

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"